### PR TITLE
Add DS Wizard as a FAIR data management planning tool

### PR DESCRIPTION
**Pull request by MarekSuchanek**
Hello,

I propose to add [Data Stewardship Wizard](https://ds-wizard.org) as one of the tools that your MOOC Module covers. It is an open-source tool for planning how to work with data during and after the research with respect to the FAIR principles which is in our opinion crucial part of "reproducible research". In case of need, we can provide additional materials and help to include it in the course...

Best regards,
Marek 😄

### CODE REVIEW

**Comment by Protohedgehog** [comment]
Awesome, thanks for this!!!

**Comment by jcolomb** [comment]
Hey, this seems more to be for module 4, consider reverting?

**Comment by MarekSuchanek** [comment]
Hello @jcolomb, I've created a new PR in Module 4. It is probably applicable in both modules, since you should consider reproducibility of research during data management planning but it depends on what details will be this course focused. Even "data management" is one of the things noted in "Learning outcomes"...

**Comment by jcolomb** [comment]
I had a look at the tool, it is indeed also interesting here.

the two modules are indeed quite related: no reproducible reports without managed (computer readable) data :)

**Pull request merged**
